
spring:
  application:
    name: ai
  ai:
    google:
      genai:
        project-id: ${GEMINI_FLASH_3_PROJECT_ID}
        api-key: ${GEMINI_FLASH_3_API_KEY}
        chat:
          options:
            model: gemini-3-flash-preview
content:
   pipeline:
     artifacts:
       root-dir: ./pipeline-artifacts

logging:
  level:
    org:
      springframework:
        security: DEBUG # or trace

rsa:
  public-key: classpath:keys/public.pem

server:
  port: 8083